# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='physician_id',
            new_name='physician',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='physician',
            old_name='physician_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physician',
            name='physician',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
