# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20160516_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='physician',
        ),
    ]
