# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20160517_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Physician'),
        ),
    ]
