# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20160518_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='datetime'),
        ),
    ]
